
import pandas as pd
from modules.youtube_summarizer.src.utils.psql_client import PSQLClient
from modules.matcher.testing_results_unit_converter import TestingResultsUnitConverter
import os

class TestingObjectMatcher:
    def __init__(self):
        self.psql_client = PSQLClient(os.getenv("PSQL_CONNECTION_STRING"))
        # Initialize unit converter
        connection_string = os.getenv("PSQL_CONNECTION_STRING")
        if connection_string:
            self.unit_converter = TestingResultsUnitConverter(connection_string)
        else:
            self.unit_converter = None
        
        # Mapping of normalized_test_object to (main_unit, unit_category)
        # This defines the preferred unit for each normalized test object
        # Generated by analyzing actual database data
        self._main_unit_mapping = {
            "ALT": ("U/L", "Enzyme Activity"),
            "AST": ("U/L", "Enzyme Activity"),
            "CRP": ("mg/L", "Mass Concentration"),
            "CRP (hs)": ("mg/L", "Mass Concentration"),
            "Chloride": ("mmol/L", "Molar Concentration"),
            "Chloride (serum)": ("mmol/L", "Molar Concentration"),
            "Cortisol (serum)": ("nmol/L", "Molar Concentration"),
            "Creatinine": ("µmol/L", "Molar Concentration"),
            "Ferritin": ("ng/mL", "Mass Concentration"),
            "Folate (RBC)": ("%", "Percentage"),
            "Folate (Serum)": ("ng/mL", "Mass Concentration"),
            "Free Testosterone": ("nmol/L", "Molar Concentration"),
            "Free Testosterone Index": ("%", "Percentage"),
            "GGT": ("U/L", "Enzyme Activity"),
            "Glucose": ("mmol/L", "Molar Concentration"),
            "Ionized Calcium": ("mmol/L", "Molar Concentration"),
            "Magnesium": ("mmol/L", "Molar Concentration"),
            "Potassium": ("mmol/L", "Molar Concentration"),
            "SHBG": ("nmol/L", "Molar Concentration"),
            "Sodium": ("mmol/L", "Molar Concentration"),
            "Total Cholesterol": ("mmol/L", "Molar Concentration"),
            "Total Testosterone": ("ng/mL", "Mass Concentration"),
            "Urea": ("mmol/L", "Molar Concentration"),
            "Uric Acid": ("µmol/L", "Molar Concentration"),
            "Vitamin B12": ("pg/mL", "Mass Concentration"),
            "Vitamin D": ("ng/mL", "Mass Concentration"),
            "Vitamin D (25-OH)": ("ng/mL", "Mass Concentration"),
            # Blood cell counts
            "Atypical Lymphocytes": ("%", "Percentage"),
            "Basophils (Bas#)": ("10^9/L", "Cell Count"),
            "Basophils (abs.)": ("10^9/L", "Cell Count"),
            "Eosinophils (Eos#)": ("10^9/L", "Cell Count"),
            "Eosinophils (abs.)": ("10^9/L", "Cell Count"),
            "Granulocytes (GRA)": ("10^9/L", "Cell Count"),
            "Immature granulocytes (abs.)": ("10^9/L", "Cell Count"),
            "Large Immature Cells": ("%", "Percentage"),
            "Lymphocytes (LYM#)": ("10^9/L", "Cell Count"),
            "Lymphocytes (LYM)": ("10^9/L", "Cell Count"),
            "Lymphocytes (abs.)": ("10^9/L", "Cell Count"),
            "Monocytes (MID)": ("10^9/L", "Cell Count"),
            "Monocytes (MON#)": ("10^9/L", "Cell Count"),
            "Neutrophils (Neu#)": ("10^9/L", "Cell Count"),
            "Neutrophils (abs.)": ("10^9/L", "Cell Count"),
            "P-LCC": ("10^9/L", "Cell Count"),
            "Platelets (PLT)": ("10^9/L", "Cell Count"),
            "RBC": ("10^12/L", "Cell Count"),
            "WBC": ("10^9/L", "Cell Count"),
            # Red blood cell parameters
            "Mean Corpuscular Hemoglobin (MCH)": ("pg", "Mass"),
            "Mean Corpuscular Volume (MCV)": ("fL", "Volume"),
            "Mean Platelet Volume (MPV)": ("fL", "Volume"),
            "Mean corpuscular hemoglobin (MCH)": ("pg", "Mass"),
            "Mean corpuscular volume (MCV)": ("fL", "Volume"),
            "Mean platelet volume (MPV)": ("fL", "Volume"),
            "Red Cell Distribution Width - CV (RDW-CV)": ("%", "Percentage"),
            "Red Cell Distribution Width - SD (RDW-SD)": ("fL", "Volume"),
            "Red cell distribution width (RDW-CV)": ("%", "Percentage"),
            "Red cell distribution width (RDW-SD)": ("fL", "Volume"),
            # Other parameters
            "HbA1c": ("%", "Percentage"),
            "P-LCR": ("%", "Percentage"),
            "PCT": ("%", "Percentage"),
            "PDW": ("%", "Percentage"),
        }
        
        # Mapping of normalized_test_object to reference value in main unit
        # Reference values are in the same unit as defined in _main_unit_mapping
        # Generated by analyzing actual database data and converting to main units
        self._main_reference = {
            "ALT": 41.0,
            "AST": 40.0,
            "Atypical Lymphocytes": 0.0,
            "Basophils (Bas#)": 0.0,
            "Basophils (abs.)": 0.01,
            "CRP": 5.0,
            "CRP (hs)": 1.0,
            "Chloride": 95.0,
            "Chloride (serum)": 95.0,
            "Cortisol (serum)": 334.5,
            "Creatinine": 62.0,
            "Eosinophils (Eos#)": 0.02,
            "Eosinophils (abs.)": 0.04,
            "Ferritin": 30.0,
            "Folate (RBC)": 36.0,
            "Folate (Serum)": 3.89,
            "Free Testosterone": 0.198,
            "Free Testosterone Index": 35.0,
            "GGT": 8.0,
            "Glucose": 1.555,
            "Granulocytes (GRA)": 2.0,
            "HbA1c": 4.8,
            "Immature granulocytes (abs.)": 0.06,
            "Ionized Calcium": 1.1,
            "Large Immature Cells": 0.0,
            "Lymphocytes (LYM#)": 0.82,
            "Lymphocytes (LYM)": 0.6,
            "Lymphocytes (abs.)": 1.32,
            "Magnesium": 0.66,
            "Mean Corpuscular Hemoglobin (MCH)": 27.0,
            "Mean Corpuscular Volume (MCV)": 77.0,
            "Mean Platelet Volume (MPV)": 9.0,
            "Mean corpuscular hemoglobin (MCH)": 26.5,
            "Mean corpuscular volume (MCV)": 77.0,
            "Mean platelet volume (MPV)": 7.0,
            "Monocytes (MID)": 0.1,
            "Monocytes (MON#)": 0.16,
            "Neutrophils (Neu#)": 1.8,
            "Neutrophils (abs.)": 1.78,
            "P-LCC": 30.0,
            "P-LCR": 13.0,
            "PCT": 0.1,
            "PDW": 10.0,
            "Platelets (PLT)": 150.0,
            "Potassium": 3.5,
            "RBC": 4.15,
            "Red Cell Distribution Width - CV (RDW-CV)": 12.0,
            "Red Cell Distribution Width - SD (RDW-SD)": 35.0,
            "Red cell distribution width (RDW-CV)": 10.0,
            "Red cell distribution width (RDW-SD)": 36.0,
            "SHBG": 18.3,
            "Sodium": 130.0,
            "Total Cholesterol": 4.5,
            "Total Testosterone": 2.49,
            "Urea": 2.76,
            "Uric Acid": 202.3,
            "Vitamin B12": 197.0,
            "Vitamin D": 30.0,
            "Vitamin D (25-OH)": 30.0,
            "WBC": 4.0,
        }
            

    def _normalize_test_object(self,df: pd.DataFrame, column: str = "testing_object") -> pd.DataFrame:
        """
        Normalize lab test names using safe, rule-based mappings.
        Adds a new column: 'normalized_test_object'.
        
        Parameters:
            df: pandas DataFrame containing the column with test names
            column: name of the column to normalize (default: 'testing_object')

        Returns:
            DataFrame with an additional 'normalized_test_object' column.
        """

        def norm(value: str) -> str:
            if value is None:
                return None

            v = value.strip().lower()

            # -------------------------------------------------------------
            # Vitamin B12
            # -------------------------------------------------------------
            if any(x in v for x in [
                "vitamin b12", "vitamin b-12", "vitamin b 12", "cyanocobalamin"
            ]):
                return "Vitamin B12"

            if "holotranscobalamin" in v or "active" in v and "b12" in v:
                return "Vitamin B12 Active"

            # -------------------------------------------------------------
            # Vitamin D
            # -------------------------------------------------------------
            if "25-hydroxy" in v or "vitamin d total" in v:
                return "Vitamin D (25-OH)"

            if v.startswith("vitamin d"):
                return "Vitamin D"

            # -------------------------------------------------------------
            # Folate / Folic Acid
            # -------------------------------------------------------------
            if "folic acid" in v or "folate (serum)" in v:
                return "Folate (Serum)"

            if "folate (whole blood" in v or "erythrocyte concentration" in v or "hematocrit" in v:
                return "Folate (RBC)"

            # -------------------------------------------------------------
            # Testosterone
            # -------------------------------------------------------------
            if "free testosterone index" in v:
                return "Free Testosterone Index"

            if "free testosterone" in v:
                return "Free Testosterone"

            if "total testosterone" in v:
                return "Total Testosterone"

            if v == "testosterone":
                return "Total Testosterone"

            # -------------------------------------------------------------
            # SHBG
            # -------------------------------------------------------------
            if "sex hormone-binding globulin" in v or v.startswith("shbg"):
                return "SHBG"

            # -------------------------------------------------------------
            # Thyroid markers
            # -------------------------------------------------------------
            if v in ("tsh", "thyroid stimulating hormone"):
                return "TSH"

            if "free thyroxine" in v or v == "ft4":
                return "Free T4"

            if "anti-thyroid peroxidase" in v:
                return "Anti-TPO"

            # -------------------------------------------------------------
            # Liver enzymes
            # -------------------------------------------------------------
            if v in ("ast", "aspartate aminotransferase"):
                return "AST"

            if v == "alt":
                return "ALT"

            if v == "ggt" or "gamma-glutamyl transferase" in v:
                return "GGT"

            # -------------------------------------------------------------
            # Bilirubin
            # -------------------------------------------------------------
            if "total bilirubin" in v:
                return "Total Bilirubin"

            if "direct bilirubin" in v:
                return "Direct Bilirubin"

            if "indirect bilirubin" in v:
                return "Indirect Bilirubin"

            # -------------------------------------------------------------
            # CRP
            # -------------------------------------------------------------
            if "c-reactive protein (high sensitivity" in v:
                return "CRP (hs)"

            if "c-reactive protein" in v:
                return "CRP"

            # -------------------------------------------------------------
            # Glucose metabolism
            # -------------------------------------------------------------
            if "glycated hemoglobin" in v or "hba1c" in v:
                return "HbA1c"

            if v == "glucose":
                return "Glucose"

            if v == "insulin":
                return "Insulin"

            # -------------------------------------------------------------
            # Cortisol
            # -------------------------------------------------------------
            if "cortisol" in v:
                return "Cortisol (serum)"

            # -------------------------------------------------------------
            # ESR
            # -------------------------------------------------------------
            if "erythrocyte sedimentation rate" in v or "esr" in v:
                return "ESR"

            # -------------------------------------------------------------
            # RBC
            # -------------------------------------------------------------
            if "erythrocytes" in v or "red blood cells" in v or v == "rbc":
                return "RBC"

            # -------------------------------------------------------------
            # WBC
            # -------------------------------------------------------------
            if "white blood cells" in v or "leukocytes" in v or v == "wbc":
                return "WBC"

            # -------------------------------------------------------------
            # Atypical lymphocytes
            # -------------------------------------------------------------
            if "atypical lymphocytes" in v:
                return "Atypical Lymphocytes"

            # -------------------------------------------------------------
            # Large immature cells
            # -------------------------------------------------------------
            if "large immature cells" in v:
                return "Large Immature Cells"

            # -------------------------------------------------------------
            # Plateletcrit
            # -------------------------------------------------------------
            if "plateletcrit" in v or "thrombocrit" in v:
                return "PCT"

            # -------------------------------------------------------------
            # PDW
            # -------------------------------------------------------------
            if "platelet distribution width" in v:
                return "PDW"

            # -------------------------------------------------------------
            # P-LCR
            # -------------------------------------------------------------
            if "large platelet ratio" in v:
                return "P-LCR"

            # -------------------------------------------------------------
            # P-LCC
            # -------------------------------------------------------------
            if "large platelet count" in v:
                return "P-LCC"

            # -------------------------------------------------------------
            # pH groups
            # -------------------------------------------------------------
            if v in ("ph", "blood ph") or "reaction (ph" in v:
                return "pH"

            # -------------------------------------------------------------
            # Pancreatic elastase
            # -------------------------------------------------------------
            if "pancreatic elastase" in v:
                return "Pancreatic Elastase"

            # -------------------------------------------------------------
            # Default: return original
            # -------------------------------------------------------------
            return value

        # apply normalization
        df["normalized_test_object"] = df[column].apply(norm)
        return df

    def _normalize_unit_name(self, unit: str) -> str:
        """
        Normalize unit names to handle common variations.
        e.g., 'mcg/dL' -> 'µg/dL', 'mcg/L' -> 'µg/L', etc.
        
        Parameters:
            unit: The unit string to normalize
        
        Returns:
            Normalized unit string
        """
        if unit is None or pd.isna(unit):
            return unit
        
        unit_str = str(unit).strip()
        
        # Common unit variations mapping
        # 'mcg' is often used instead of 'µg' (micrograms)
        unit_str = unit_str.replace('mcg', 'µg')
        unit_str = unit_str.replace('MCG', 'µg')
        unit_str = unit_str.replace('Mcg', 'µg')
        
        # Handle case variations for common units
        # Normalize to standard case (e.g., 'L' not 'l', but keep 'µ' lowercase)
        unit_str = unit_str.replace('/l', '/L')
        unit_str = unit_str.replace('/ml', '/mL')
        unit_str = unit_str.replace('/dl', '/dL')
        
        return unit_str

    def _filter_main_unit(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Filter and convert units to main/preferred units for each normalized test object.
        Rows that cannot be converted to the main unit are excluded.
        
        Parameters:
            df: pandas DataFrame containing columns:
                - normalized_test_object: The normalized test object name
                - result_unit: The current unit
                - result_value: The result value to convert
        
        Returns:
            DataFrame with filtered rows and converted values/units.
            Rows that couldn't be converted are excluded.
        """
        if df.empty:
            return df
        
        if self.unit_converter is None:
            print("Warning: Unit converter not available, skipping unit filtering")
            return df
        
        # Required columns check
        required_columns = ["normalized_test_object", "result_unit", "result_value"]
        missing_columns = [col for col in required_columns if col not in df.columns]
        if missing_columns:
            raise ValueError(f"DataFrame must contain columns: {required_columns}. Missing: {missing_columns}")
        
        # Create a copy to avoid modifying the original
        result_df = df.copy()
        
        # Normalize unit names first
        result_df["result_unit"] = result_df["result_unit"].apply(self._normalize_unit_name)
        
        # Track rows to keep
        keep_mask = pd.Series([True] * len(result_df), index=result_df.index)
        
        # Process each row
        for idx, row in result_df.iterrows():
            normalized_test_object = row["normalized_test_object"]
            current_unit = row["result_unit"]
            current_value = row["result_value"]
            
            # Skip if normalized_test_object is not in mapping
            if normalized_test_object not in self._main_unit_mapping:
                # If no mapping exists, keep the row as-is
                continue
            
            # Get main unit and category
            main_unit, unit_category = self._main_unit_mapping[normalized_test_object]
            
            # Skip if unit is None or NaN
            if pd.isna(current_unit) or current_unit is None:
                # Keep rows with no unit (can't filter them)
                continue
            
            # Skip if value is None or NaN
            if pd.isna(current_value) or current_value is None:
                # Keep rows with no value
                continue
            
            # If unit already matches main unit, keep the row
            if current_unit == main_unit:
                continue
            
            # Try to convert to main unit
            try:
                converted_value = self.unit_converter.convert(
                    unit_category=unit_category,
                    unit=current_unit,
                    unit_destination=main_unit,
                    value=float(current_value)
                )
                
                # If conversion failed (returned None), exclude this row
                if converted_value is None:
                    keep_mask.loc[idx] = False
                    continue
                
                # Update the value and unit
                result_df.at[idx, "result_value"] = converted_value
                result_df.at[idx, "result_unit"] = main_unit
                
            except Exception as e:
                # If conversion failed with exception, exclude this row
                print(f"Warning: Failed to convert unit for {normalized_test_object}: {current_unit} -> {main_unit}. Error: {e}")
                keep_mask.loc[idx] = False
        
        # Filter rows
        filtered_df = result_df[keep_mask].copy()
        
        return filtered_df

if __name__ == "__main__":
    # Test normalization
    df = pd.DataFrame({
        "testing_object": ["cortisol", "cortisol (free)", "Cortisol"]
    })
    df = TestingObjectMatcher()._normalize_test_object(df)
    print("Normalized test objects:")
    print(df)
    
    # Test unit filtering
    print("\n" + "="*50)
    print("Testing unit filtering:")
    matcher = TestingObjectMatcher()
    test_df = pd.DataFrame({
        "normalized_test_object": ["Cortisol (serum)", "Cortisol (serum)", "Cortisol (serum)"],
        "result_unit": ["nmol/L", "µg/dL", "nmol/L"],
        "result_value": [500.0, 18.0, 600.0]
    })
    print("\nOriginal DataFrame:")
    print(test_df)
    filtered_df = matcher._filter_main_unit(test_df)
    print("\nFiltered DataFrame (µg/dL should be excluded as it can't be converted):")
    print(filtered_df)


"""

external test object table:
id, name
1, cortisol
2, cortisol (free)
3, Cortisol


** Option 1: matching id mapping
internal test object table:
id, name
1, cortisol
2, vitamin d

mapping:
external_id, internal_id
1, 1
2, 1
3, 1

** Option 2: "live matching"
- on API live transform values
- no specific internal id needed

rules:
- remove () and everything after it
- lower case
- remove special characters
- replace - and _  with whitespace
- remove whitespace

- issue: which value to display in the frontend?


Option 3: view transformation (psql level)
- on view level have clear definitions and clear words

Option 4: pandas transformation (api level)


"""